# Getting memory and CPU status playbook
---
- hosts: "all"
  become: true
  tasks:
    - name: "cpu status"
      win_command: wmic cpu get loadpercentage
      register: cpu_results

    - name: "memory status"
      win_command: systeminfo
      register: memory_results 
