# Install docker+docker-compose and deploy Prometheus+grafana
---
- hosts: "all"
  become: true
  tasks:
  - name: "Install docker via apt"
    apt:
      name: "docker"
      state: "latest"
      update_cache: true
  - name: "Install docker compose via apt"
    apt:
      name: "docker-compose"
      state: "latest"
      update_cache: true 
      
  - name: "Clone git repository"
    git:
      repo: "https://github.com/M-boxx/prometheus"
      dest: "/etc/prometheus/"
      clone: yes
      update: yes
      force: yes 
      
  - name: "Stop docker containers"
    community.docker.docker_compose:
      project_src: "/etc/prometheus/"
      build: false
      stopped: true
    register: output    

  - name: "Deploy Grafana+Prometheus container"
    community.docker.docker_compose:
      project_src: "/etc/prometheus/"
    register: output
